// Generates ../src/xkcd.rs from the KSA decompiled source's KSAColor.Xkcd block.
//
// The XKCD color survey palette ships inside KSA as `KSAColor.Xkcd.<Name> => float3.Rgb(r, g, b)`
// with the channels written as C# float literals — some are plain decimals, some are exact
// fractions (`38f / 85f`), a few even involve `Math.E`. We evaluate each channel expression to a
// concrete 0..1 value and emit a flat Rust table. Run from the repo with Bun:
//
//   bun examples/dancy-party-rs/tools/gen_xkcd.ts
//
// This is a one-shot build aid; the generated src/xkcd.rs is committed, so contributors don't need
// Bun or the decompiled sources to build the example.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const src = join(here, "..", "..", "..", "thirdparty", "ksa", "KSA", "KSAColor.cs");
const out = join(here, "..", "src", "xkcd.rs");

const text = readFileSync(src, "utf8");

// Slice out just the `public static class Xkcd { ... }` body so we don't pick up the F0 presets
// above it or the file-scope `float4`/`byte4` readonly fields below it.
const start = text.indexOf("public static class Xkcd");
if (start < 0) throw new Error("Xkcd class not found in " + src);
const body = text.slice(start);

// Evaluate one C# float channel expression (e.g. "38f / 85f", "(float)Math.E * 105f / 302f").
function evalChannel(expr: string): number {
  const js = expr
    .replace(/\(float\)/g, "")
    .replace(/Math\.E/g, String(Math.E))
    .replace(/([0-9.]+)f/g, "$1")
    .trim();
  const v = Function(`"use strict"; return (${js});`)() as number;
  if (!Number.isFinite(v)) throw new Error(`bad channel expr: ${expr} -> ${js}`);
  return v;
}

// Renders a number as a valid Rust f32 literal — always with a decimal point so `0`/`1` don't parse
// as integers in an `[f32; 3]` array.
function rustF32(v: number): string {
  const s = String(v);
  return /[.eE]/.test(s) ? s : s + ".0";
}

const re = /Color\.Preset\s+(\w+)\s*=>\s*float3\.Rgb\(([^;]+)\)\s*;/g;
const rows: string[] = [];
let m: RegExpExecArray | null;
while ((m = re.exec(body)) !== null) {
  const name = m[1];
  const parts = m[2].split(",");
  if (parts.length !== 3) throw new Error(`expected 3 channels for ${name}, got ${parts.length}`);
  const [r, g, b] = parts.map(evalChannel);
  rows.push(`    ("${name}", [${rustF32(r)}, ${rustF32(g)}, ${rustF32(b)}]),`);
}

if (rows.length < 800) throw new Error(`only parsed ${rows.length} colors — something is wrong`);

const header = `//! The XKCD color-survey palette, lifted verbatim from KSA's \`KSAColor.Xkcd\`.
//!
//! @generated by tools/gen_xkcd.ts from thirdparty/ksa/KSA/KSAColor.cs — do not edit by hand.
//! Each entry is \`(PascalCaseName, [r, g, b])\` with channels in 0..1. ${rows.length} colors.

// A few channels are exact KSA fraction evaluations (e.g. 38/85), so their literals carry more digits
// than an f32 keeps — intentional and harmless (each rounds to the nearest f32).
#![allow(clippy::excessive_precision)]

/// Every XKCD preset KSA ships, as \`(name, rgb_0_1)\`. The names are PascalCase as in the C# source;
/// [\`crate::color::humanize\`] turns them into spaced lowercase for display and fuzzy search.
pub static XKCD: &[(&str, [f32; 3])] = &[
`;

writeFileSync(out, header + rows.join("\n") + "\n];\n");
console.log(`wrote ${rows.length} colors to ${out}`);
