<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Library</OutputType>
        <AssemblyName>gatOS.Paint.Tests</AssemblyName>
        <RootNamespace>gatOS.Paint.Tests</RootNamespace>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
    </PropertyGroup>
    <ItemGroup><ProjectReference Include="..\gatOS.Paint\gatOS.Paint.csproj" /></ItemGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
        <PackageReference Include="NUnit" Version="4.2.2" />
        <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
        <PackageReference Include="NUnit.Analyzers" Version="4.3.0" PrivateAssets="all" />
    </ItemGroup>
    <ItemGroup><Using Include="NUnit.Framework" /></ItemGroup>
</Project>
